### ISSUE TITLE
Installation Guide Needed

### ISSUE THREAD

**Issue by padagoal** [kelp404/electron-s3-file-manager#63]
Hi mate!

You can add a installation guide, where to put or how to put the database credentials to running the migrations or how to put the Access Key?

**Comment by kelp404** [comment]
Hello @padagoal ,

1. How to run migration?
The app will run database migration scripts when start.
https://github.com/kelp404/electron-s3-file-manager/blob/v0.1.1/src/main-process/index.js#L88

2. How to set access key?
Go to settings tab.
<img width="937" alt="截圖 2022-09-15 上午9 55 22" src="https://user-images.githubusercontent.com/1680868/190295460-40a21487-7449-46c9-bf8f-1c282a46737f.png">
